import Head from 'next/head'
import Link from 'next/link'

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>關於</h1>
        <hr />
        <Link href="/">
          <a>回到主頁面</a>
        </Link>
      </div>
    </div>
  )
}
