import Head from 'next/head'

export default function Home(props) {
  const { datalist } = props
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ul>
          {datalist.map((ele) => (
            <li key={ele}>{ele}</li>
          ))}
        </ul>
      </div>
    </div>
  )
}

// getStaticProps 在服務器端會執行，在編譯(build)時也會執行
export async function getStaticProps(constext) {
  console.log('Home getStaticProps is runing...')
  return {
    props: {
      datalist: ['react', 'vue', 'angular'],
    },
  }
}
